#   branches:
#     - main  # 每次代码推送到 main 分支时也会触发

  push:
    branches:
      - main  # 只在主分支提交时触发
  # push:
  #  branches:
  #    - main  # 只在主分支提交时触发

jobs:
sign-in:
runs-on: ubuntu-latest

steps:
- name: Check out code
uses: actions/checkout@v2

- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: "3.8"  # 你可以选择所需的 Python 版本

- name: Install dependencies
run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt  # 安装依赖

   - name: Set up environment variables
run: |
       echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> $GITHUB_ENV
       echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}" >> $GITHUB_ENV
       echo "HTTP_PROXY=${{ secrets.HTTP_PROXY }}" >> $GITHUB_ENV
